name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: sickcodes/docker-osx:latest
    steps:
    - uses: ./start.sh
   
